### POST request to create a new patient
POST http://localhost:8080/api/patients/create
Content-Type: application/json

{
    "firstName": "Michael",
    "lastName": "Johnson",
    "birthDate": "1965-10-02",
    "email": "mike.johnson@email.com",
    "address": {
        "street": "11 Banning St",
        "city": "Seaside",
        "state": "NSW",
        "zipCode": "2000",
        "country": "Australia"
  }
}

###