spring.application.name=patient-service

#commenting out the datasource configuration for now, as we now use docker to run the database, and the connection details are different. We will uncomment and update these properties when we switch to using the local database for development.
#spring.datasource.url=jdbc:postgresql://localhost:5433/patient_management
#spring.datasource.username=pms_user
#spring.datasource.password=pmspassword
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto= update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=false

logging.level.root=info
