services:
  patient-management-postgres:
    image: postgres:16-alpine
    container_name: patient-management-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: patient_management
      POSTGRES_USER: pms_user
      POSTGRES_PASSWORD: pmspassword
    ports:
      - "5433:5432"
    volumes:
      - patient-management-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pms_user", "-d", "patient_management"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - patient-management-network

volumes:
  patient-management-data:
    name: patient-management-data

networks:
  patient-management-network:
    name: patient-management-network
    driver: bridge